### ISSUE TITLE
Illegal Instruction on MR3020

### ISSUE THREAD

**Issue by MerGr** [lanrat/openwrt-tailscale-repo#1]
Installation successful, but the /etc/init.d/tailscale and tailscale up errors out with "Illegal Instruction", the device is running a modified 19.07 OpenWRT extroot ready firmware, the device is a mips_24kc ar9330 chipset

**Comment by lanrat** [comment]
Thanks for the bug report. I think I just fixed this in e16ac62a004ee6d8ecb0ff6be21af729a7e470ee. Can you re-install and report back?

**Comment by MerGr** [comment]
Installed and it works. Thank you.
