### ISSUE TITLE
GL-iNet GL-SFT1200 (SiFlower) support

### ISSUE THREAD

**Issue by iGerman00** [lanrat/openwrt-tailscale-repo#2]
It's a small router that runs on the mips-siflower architecture and their fork of OpenWRT 18.06. It's different from mipsle, but if you compile a statically linked binary, that works. 
[I wrote a guide on how to set it up](https://gist.github.com/iGerman00/b45f78685f7db0fa264edf7a0d81bd50), but there's a problem with UPX. Maybe you can improve on it? I don't have any experience scripting for OpenWRT myself.

**Comment by lanrat** [comment]
@iGerman00 how is it differnt than `mipsle`? I don't have that router myself, but looking over your gist, you do set `GOOS=linux GOARCH=mipsle` which should already exist in this repository.

Do you get any errors when installing/using tailscale from this repository?

**Comment by iGerman00** [comment]
> Do you get any errors when installing/using tailscale from this repository?

Huh, I guess I haven't actually tried it. Sort of assumed it doesn't work because I've seen many reports of mipsle software not working. If I recall correctly, the compiled binary has to be statically linked, because it fails to link ld.so on this particular variation of mips. I'll try now, though.

**Comment by iGerman00** [comment]
the OpenWRT version is a small concern since this router runs on a fork of 18.06, and probably won't have anything newer

**Comment by iGerman00** [comment]
![WindowsTerminal (2023-07-13 19։40։52)](https://github.com/lanrat/openwrt-tailscale-repo/assets/36676880/f5dd5d51-28ba-4990-add9-b06ed58cdc2b)
No valid architecture.

The output of `opkg print-architecture`:
```
arch all 1
arch noarch 1
arch mips_siflower 10
```

**Comment by lanrat** [comment]
I've never heard of the `mips_siflower` arch before, so I see your point. A quick search to determine golang support returns your exiting research https://github.com/golang/go/issues/61254. :)

I tried adding build support for mips_siflower in https://github.com/lanrat/openwrt-tailscale-repo/commit/33cc466cc99c26c43bd6220fd4b1c23393f61596 which should be in the repo now. Can you give it another try?

**Comment by iGerman00** [comment]
Actually seems to be functional! 
~~One thing, the configs can't be stored in /var/ since that's RAM on this router. /etc/ seems to be persistent (check my guide's init.d file). /root/ also works and might be better for configs, since it's the user directory.~~
nvm you already handle that

I verified with the [additional firewall config steps](https://openwrt.org/docs/guide-user/services/vpn/tailscale/start#how_to_setup_a_subnet_routerexit_node), and it seems to be working perfectly fine. I can at the very least ping my PC from my mobile network. Can't use KDE Connect, but RDP works just fine too!

Exit node, however, doesn't work, and just hangs.

**Comment by iGerman00** [comment]
The binary is still huge at almost 30MB in size, which is not very good for small devices. But I think that's on Tailscale, and potentially UPX to fix.
![WindowsTerminal (2023-07-14 03։24։31)](https://github.com/lanrat/openwrt-tailscale-repo/assets/36676880/0bc4e128-fe75-47e7-bc45-c5eb8c0e77cc)

**Comment by lanrat** [comment]
I'm glad to hear it works.

The binary size is not something I can control.
I've also had issues using it as an exit node. I suspect its a openwrt firewall issue, but I have not figured it out yet. 

Since the original issue was resolved I'll close this, but feel free to post again if you find anything else.
