### ISSUE TITLE
Illegal instruction on GL-MT1300

### ISSUE THREAD

**Issue by gite3** [lanrat/openwrt-tailscale-repo#3]
https://lanrat.github.io/openwrt-tailscale-repo/packages/19.07/tailscale_1.46.0_mipsel_24kc.ipk

Installation on Gl.inet GL-MT1300 with stock firmware results in "Illegal instruction"

root@mt1300:\~# echo "src/gz openwrt-tailscale https://lanrat.github.io/openwrt-tailscale-repo/packages/1
9.07" >> "/etc/opkg/customfeeds.conf"
root@mt1300:\~# opkg update ; opkg install tailscale
Downloading https://lanrat.github.io/openwrt-tailscale-repo/packages/19.07/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt-tailscale
Downloading https://fw.gl-inet.com/releases/v19.07.8/packages-3.0/ramips/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/glinet_packages
Downloading https://fw.gl-inet.com/releases/v19.07.8/packages-3.0/ramips/glinet/Packages.gz
Updated list of available packages in /var/opkg-lists/glinet_private
Downloading https://fw.gl-inet.com/releases/v19.07.8/kmod-3.0-newdriver/ramips/mt7621/Packages.gz
Updated list of available packages in /var/opkg-lists/glinet_kmod
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Package tailscale version 1.46.0 has no valid architecture, ignoring.
Installing tailscale (1.46.0) to root...
Downloading https://lanrat.github.io/openwrt-tailscale-repo/packages/19.07/tailscale_1.46.0_mipsel_24kc.ipk
Configuring tailscale.
Illegal instruction

**Comment by lanrat** [comment]
Can you run `opkg print-architecture` and post the response?

**Comment by gite3** [comment]
root@e750:\~# opkg print-architecture
arch all 1
arch noarch 1
arch mips_24kc 10

**Comment by gite3** [comment]
I made a build that works by setting 'GOMIPS=softfloat', similar to the solution I found here:
https://github.com/lanrat/openwrt-tailscale-repo/issues/1

**Comment by lanrat** [comment]
~~I was just researching that. I'll add that to the `mips_24kc` arch.~~

I have not yet been able to find a good definition for which openwrt architectures need hard/soft float.~~

**Comment by lanrat** [comment]
@gite3 your `opkg print-architecture` lists `mips_24kc` which already has `GOMIPS=softfloat` set.

But your opkg install tried to install  `tailscale_1.46.0_mipsel_24kc.ipk` which is for `mipsel_24kc`

Are these on the same device?

**Comment by gite3** [comment]
Sorry, my bad. The previous output was from e750, which works with your build.
Here's the correct output:
root@mt1300:\~# opkg print-architecture
arch all 1
arch noarch 1
arch mipsel_24kc 10

**Comment by gite3** [comment]
root@mt1300:\~# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='19.07.8'
DISTRIB_REVISION='r11364-ef56c85848'
DISTRIB_TARGET='ramips/mt76x8'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 19.07.8 r11364-ef56c85848'
DISTRIB_TAINTS='busybox'

**Comment by lanrat** [comment]
Just added that.
