### ISSUE TITLE
mips_siflower

### ISSUE THREAD

**Issue by SeseaIOI** [lanrat/openwrt-tailscale-repo#4]
mips_siflower

**Comment by lanrat** [comment]
Is this a new architecture request?

**Comment by SeseaIOI** [comment]
Yea Please. It is for GL-iNet SFT1200 OPAL

**Comment by lanrat** [comment]
`mips_siflower` is already a supported architecture: https://github.com/lanrat/openwrt-tailscale-repo/blob/main/build.sh#L15

https://lanrat.github.io/openwrt-tailscale-repo/packages/19.07/tailscale_1.68.0_mips_siflower.ipk
